### ISSUE TITLE
Installation with homebrew? 

### ISSUE THREAD

**Issue by ghost** [FalseDev/instant-api-client#2]
Now you can obviously download python packages (pip packages) with homebrew. But when I download it from homebrew, says that some classes don't exist. 

Looking at the commits, somehow the APIRouter class is not available when you install with homebrew. 
So- what do I exactly do here? 
Do I clone the repo?

I think you should reach out to homebrew and create an installation which installs the latest version of this github repo.

**Comment by FalseDev** [comment]
I will look into this and keep you posted!

**Comment by ghost** [comment]
> I will look into this and keep you posted!

Thanks

**Comment by FalseDev** [comment]
Closing the issue as the module isn't standalone and is meant to be used as a builder tool for other modules.

Hence I believe pip installation is fine.
